added a 'name' prop
ekeric13/react-star-ratings pull request #7
Opened 2018-06-04 21:44 UTC by monikamangal123

added a 'name' prop to make the star-rating div identifiable. In case we have more than one star-rating component in the code, there is no way to differentiate between them. By adding 'name' prop one can make out which star-rating component is being changed inside the changeRating event.

2018-06-05 07:48 UTC, ekeric13 commented
Let me take a look at it this weekend. Will need to do a minor version but something like this is definitely useful.

2018-06-10 08:29 UTC, monikamangal123 commented
@ekeric13 hey, did you get the chance to look at it?

2018-06-10 18:23 UTC, ekeric13 requested changes
hey @monikamangal123 , thanks for following up. Took a look at it and I am suggesting a small change but overall it looks great.

Also it would be great if you could add in the name prop to the readme.md and update the docs.

2018-06-10 18:23 UTC, ekeric13 commented on src/star-ratings.js
> +          changeRating={changeRating ? () => changeRating(name, starRating) : null}
Is there any reason that you would want the first arg to be name instead of rating in the changeRating callback?

I think we should keep the first arg `rating` to keep it consistent with older versions, and since not everyone will have a `name` prop, but everyone will need a `rating`.

2018-06-11 17:34 UTC, monikamangal123 commented on src/star-ratings.js
> +          changeRating={changeRating ? () => changeRating(name, starRating) : null}
there is no particular reason for it to be first argument, hence I will update it 👍

2018-06-12 02:32 UTC, ekeric13 approved these changes

2018-06-12 02:32 UTC, merged

2018-06-12 02:42 UTC, ekeric13 commented
@monikamangal123 merged in =b